### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by cyouh95** [DanialStoica/f1-3-c2p1-colmar-academy#2]
The menu bar should contain the following items in each of the `a` tags: `On campus`, `Online`, `For companies`, `Sign in`

https://github.com/DanialStoica/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/index.html#L17-L28

**Comment by DanialStoica** [comment]
If I change it to that order, my menu ends up looking like this, Is there a way to fix this?
![capture](https://user-images.githubusercontent.com/32824183/34323097-0c5947a6-e7ef-11e7-9f5d-4f998b00cdaf.PNG)

**Comment by cyouh95** [comment]
It looks like this is due to the `word-spacing: 16px;` property [here](https://github.com/DanialStoica/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/stylesheet.css#L8). Remove that line and instead add some padding so there will be some spaces between each item (`padding: 5px;`).

Also, your [reset.css](https://github.com/DanialStoica/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/reset.css) file should actually not be a copy of your stylesheet. Instead, replace the content with [this](https://s3.amazonaws.com/codecademy-content/programs/react/ravenous/reset.css). (This is just for browser compatibility).

Let me know if this fixes things!

**Comment by DanialStoica** [comment]
Thank you, that worked!
